/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentandaDePartdida_VDP.java
 *
 * Created on Aug 3, 2010, 12:29:54 PM
 */

package Presentacion;

/**
 *
 * @author Isra
 */
public class VentandaDePartdida_VDP extends javax.swing.JFrame {

    /** Creates new form VentandaDePartdida_VDP */
    public VentandaDePartdida_VDP() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbTitulo = new javax.swing.JLabel();
        jbCrearParida = new javax.swing.JButton();
        jbEstadisticas = new javax.swing.JButton();
        jbCargarPartida = new javax.swing.JButton();
        jlimg1VDP = new javax.swing.JLabel();
        jlimgVDP2 = new javax.swing.JLabel();
        jlimgVDP3 = new javax.swing.JLabel();
        jbRecords = new javax.swing.JButton();
        jlimgVDP4 = new javax.swing.JLabel();
        jbMyprofile = new javax.swing.JButton();
        jlimgVDP5 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jlimgVDP6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jbTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/titulotext.png"))); // NOI18N

        jbCrearParida.setText("Crear Partida");
        jbCrearParida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearParidaActionPerformed(evt);
            }
        });

        jbEstadisticas.setText("Estadisticas");

        jbCargarPartida.setText("Cargar Partida");
        jbCargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarPartidaActionPerformed(evt);
            }
        });

        jlimg1VDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/img1VDP.png"))); // NOI18N

        jlimgVDP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/img2VDP.png"))); // NOI18N

        jlimgVDP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/img3VDP.png"))); // NOI18N

        jbRecords.setText("Records");

        jlimgVDP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/trofeoVDP.png"))); // NOI18N

        jbMyprofile.setText("MyProfile");

        jlimgVDP5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/perfilVDP.png"))); // NOI18N

        jbSalir.setText("Salir!");

        jlimgVDP6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/salirVDP.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jbCrearParida)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jlimg1VDP))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jbCargarPartida, 0, 0, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jbEstadisticas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jlimgVDP2))
                            .add(layout.createSequentialGroup()
                                .add(32, 32, 32)
                                .add(jlimgVDP3)))))
                .add(145, 145, 145)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jbRecords)
                    .add(jbMyprofile)
                    .add(jbSalir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlimgVDP6)
                    .add(jlimgVDP5)
                    .add(jlimgVDP4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(163, 163, 163))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .add(jbTitulo)
                .add(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jbTitulo)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jbCrearParida)
                            .add(jlimg1VDP)
                            .add(jbRecords))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(jbEstadisticas)
                                    .add(145, 145, 145))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jlimgVDP5)
                                    .add(jlimgVDP2)))
                            .add(jbMyprofile)))
                    .add(jlimgVDP4))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jbCargarPartida)
                        .add(jbSalir))
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jlimgVDP3))
                    .add(jlimgVDP6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCargarPartidaActionPerformed

    private void jbCrearParidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearParidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCrearParidaActionPerformed

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCargarPartida;
    private javax.swing.JButton jbCrearParida;
    private javax.swing.JButton jbEstadisticas;
    private javax.swing.JButton jbMyprofile;
    private javax.swing.JButton jbRecords;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jbTitulo;
    private javax.swing.JLabel jlimg1VDP;
    private javax.swing.JLabel jlimgVDP2;
    private javax.swing.JLabel jlimgVDP3;
    private javax.swing.JLabel jlimgVDP4;
    private javax.swing.JLabel jlimgVDP5;
    private javax.swing.JLabel jlimgVDP6;
    // End of variables declaration//GEN-END:variables

}
